version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"  # React app via Nginx
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"  # Express server
    environment:
      - NODE_ENV=production
 # Add this line
    volumes:
      - ./server:/app
    restart: unless-stopped